<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/protos/nknSigChain.proto

namespace Protos;

/**
 * Protobuf type <code>protos.SigAlgo</code>
 */
class SigAlgo
{
    /**
     * Generated from protobuf enum <code>ECDSA = 0;</code>
     */
    const ECDSA = 0;
}

