<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/protos/nknSigChain.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protos.SigChain</code>
 */
class SigChain extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 Nonce = 1;</code>
     */
    private $Nonce = 0;
    /**
     * Generated from protobuf field <code>uint32 DataSize = 2;</code>
     */
    private $DataSize = 0;
    /**
     * Generated from protobuf field <code>bytes DataHash = 3;</code>
     */
    private $DataHash = '';
    /**
     * Generated from protobuf field <code>bytes BlockHash = 4;</code>
     */
    private $BlockHash = '';
    /**
     * Generated from protobuf field <code>bytes SrcPubkey = 5;</code>
     */
    private $SrcPubkey = '';
    /**
     * Generated from protobuf field <code>bytes DestPubkey = 6;</code>
     */
    private $DestPubkey = '';
    /**
     * Generated from protobuf field <code>repeated .protos.SigChainElem Elems = 7;</code>
     */
    private $Elems;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Nonce
     *     @type int $DataSize
     *     @type string $DataHash
     *     @type string $BlockHash
     *     @type string $SrcPubkey
     *     @type string $DestPubkey
     *     @type \Protos\SigChainElem[]|\Google\Protobuf\Internal\RepeatedField $Elems
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protobuf\Protos\NknSigChain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 Nonce = 1;</code>
     * @return int
     */
    public function getNonce()
    {
        return $this->Nonce;
    }

    /**
     * Generated from protobuf field <code>uint32 Nonce = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setNonce($var)
    {
        GPBUtil::checkUint32($var);
        $this->Nonce = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 DataSize = 2;</code>
     * @return int
     */
    public function getDataSize()
    {
        return $this->DataSize;
    }

    /**
     * Generated from protobuf field <code>uint32 DataSize = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setDataSize($var)
    {
        GPBUtil::checkUint32($var);
        $this->DataSize = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes DataHash = 3;</code>
     * @return string
     */
    public function getDataHash()
    {
        return $this->DataHash;
    }

    /**
     * Generated from protobuf field <code>bytes DataHash = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDataHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->DataHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes BlockHash = 4;</code>
     * @return string
     */
    public function getBlockHash()
    {
        return $this->BlockHash;
    }

    /**
     * Generated from protobuf field <code>bytes BlockHash = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBlockHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->BlockHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes SrcPubkey = 5;</code>
     * @return string
     */
    public function getSrcPubkey()
    {
        return $this->SrcPubkey;
    }

    /**
     * Generated from protobuf field <code>bytes SrcPubkey = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSrcPubkey($var)
    {
        GPBUtil::checkString($var, False);
        $this->SrcPubkey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes DestPubkey = 6;</code>
     * @return string
     */
    public function getDestPubkey()
    {
        return $this->DestPubkey;
    }

    /**
     * Generated from protobuf field <code>bytes DestPubkey = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDestPubkey($var)
    {
        GPBUtil::checkString($var, False);
        $this->DestPubkey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protos.SigChainElem Elems = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getElems()
    {
        return $this->Elems;
    }

    /**
     * Generated from protobuf field <code>repeated .protos.SigChainElem Elems = 7;</code>
     * @param \Protos\SigChainElem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setElems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\SigChainElem::class);
        $this->Elems = $arr;

        return $this;
    }

}

