<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/protos/nknSigChain.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protos.SigChainElem</code>
 */
class SigChainElem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes Addr = 1;</code>
     */
    private $Addr = '';
    /**
     * Generated from protobuf field <code>bytes NextPubkey = 2;</code>
     */
    private $NextPubkey = '';
    /**
     * Generated from protobuf field <code>bool Mining = 3;</code>
     */
    private $Mining = false;
    /**
     * Generated from protobuf field <code>.protos.SigAlgo SigAlgo = 4;</code>
     */
    private $SigAlgo = 0;
    /**
     * Generated from protobuf field <code>bytes Signature = 5;</code>
     */
    private $Signature = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Addr
     *     @type string $NextPubkey
     *     @type bool $Mining
     *     @type int $SigAlgo
     *     @type string $Signature
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protobuf\Protos\NknSigChain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes Addr = 1;</code>
     * @return string
     */
    public function getAddr()
    {
        return $this->Addr;
    }

    /**
     * Generated from protobuf field <code>bytes Addr = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddr($var)
    {
        GPBUtil::checkString($var, False);
        $this->Addr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes NextPubkey = 2;</code>
     * @return string
     */
    public function getNextPubkey()
    {
        return $this->NextPubkey;
    }

    /**
     * Generated from protobuf field <code>bytes NextPubkey = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNextPubkey($var)
    {
        GPBUtil::checkString($var, False);
        $this->NextPubkey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool Mining = 3;</code>
     * @return bool
     */
    public function getMining()
    {
        return $this->Mining;
    }

    /**
     * Generated from protobuf field <code>bool Mining = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setMining($var)
    {
        GPBUtil::checkBool($var);
        $this->Mining = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.SigAlgo SigAlgo = 4;</code>
     * @return int
     */
    public function getSigAlgo()
    {
        return $this->SigAlgo;
    }

    /**
     * Generated from protobuf field <code>.protos.SigAlgo SigAlgo = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSigAlgo($var)
    {
        GPBUtil::checkEnum($var, \Protos\SigAlgo::class);
        $this->SigAlgo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes Signature = 5;</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->Signature;
    }

    /**
     * Generated from protobuf field <code>bytes Signature = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->Signature = $var;

        return $this;
    }

}

