<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/protos/nknSigChain.proto

namespace GPBMetadata\Protobuf\Protos;

class NknSigChain
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0adf020a2170726f746f6275662f70726f746f732f6e6b6e536967436861" .
            "696e2e70726f746f120670726f746f7322750a0c536967436861696e456c" .
            "656d120c0a044164647218012001280c12120a0a4e6578745075626b6579" .
            "18022001280c120e0a064d696e696e6718032001280812200a0753696741" .
            "6c676f18042001280e320f2e70726f746f732e536967416c676f12110a09" .
            "5369676e617475726518052001280c229c010a08536967436861696e120d" .
            "0a054e6f6e636518012001280d12100a084461746153697a651802200128" .
            "0d12100a08446174614861736818032001280c12110a09426c6f636b4861" .
            "736818042001280c12110a095372635075626b657918052001280c12120a" .
            "0a446573745075626b657918062001280c12230a05456c656d7318072003" .
            "280b32142e70726f746f732e536967436861696e456c656d2a140a075369" .
            "67416c676f12090a0545434453411000620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

